language: node_js
node_js:
- '17'
before_install:
- npm install -g @angular/cli
install: 
  - npm install
branches:
  only:
  - main
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
deploy:
  provider: heroku
  app: epam-steam-app
  api_key:
    secure: 19e832bf-8044-4721-95cb-e923e654f264
  on:
    all_branches: true
